export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const ONLINE_FRIEND_REQUEST = "ONLINE_FRIEND_REQUEST"
export const ONLINE_FRIEND_SUCCESS = "ONLINE_FRIEND_SUCCESS"
export const ONLINE_FRIEND_FAIL = "ONLINE_FRIEND_FAIL"